### ISSUE TITLE
[feature] Enable glob patterns in `config.test` / `Codecept.loadTests`

### ISSUE THREAD

**Issue by sveneisenschmidt** [Codeception/CodeceptJS#976]
Hello, first thank you for the work you have put in here!  
(This is the first part of a feature request. For the second part please go to #978.)

**Sidenote**
We at @trivago Leipzig use CodeceptJS for end-to-end testing and are working currently on a simple way to run multiple jobs in parallel without using grep and tags.

**Feature**
A first step into having a working solution is to enable CodeceptJS to load tests not only by grep/tags but also by the already working but limited glob support in  `Codecept.loadTests`. A simple modification by introducing a non-breaking change to how `glob.sync` is called would enable everyone to use glob patterns in their configuration.

The true power with this feature lies in combination with #978. If both features get accepted it will be possible do dynamically create `run-multiple` configuration by the amount of overall scenarios and distribute them evenly between a defined amount of runs. For a working examples please have a look [here](https://github.com/sveneisenschmidt/codeceptjs-boilerplate/blob/master/lib/create-multiple.js) and [here](https://github.com/sveneisenschmidt/codeceptjs-boilerplate/blob/master/codecept.conf.js).

**Technical explaination**
I'd like to propose to remove the `fsPath.resolve` call for passing the pattern to glob. This enables glob to perform a bracket expansion. To make sure that glob is still being executed in the correct directory I'd pass the `cwd` option to glob and set it to `global.codecept_dir` to basically mimic the same `fsPath.resolve` call. To have a absolute path pushed into `this.files` the second `fsPath.resolve` inside the loop is kept.

**Example**
```js
{
  "tests": "{./file1_test.js,./file2_test.js}"
}
```

**Todos**
- [x] Add `test-runner` service in `docker-compose.yml`
- [x] Write test case and verify nothing is breaking
- [x] Adapt `loadTests` function
- [x] Create a Pull Request in the fork https://github.com/sveneisenschmidt/CodeceptJS/pull/1
- [x] Feedback by maintainers
- [x] Create a Pull Request in this repository

What do you think? 

PS: If you want to see why glob support is needed please look at my demo repository:

- https://github.com/sveneisenschmidt/codeceptjs-boilerplate#todo
- https://github.com/sveneisenschmidt/codeceptjs-boilerplate/blob/master/lib/create-multiple.js
- https://github.com/sveneisenschmidt/codeceptjs-boilerplate/blob/master/codecept.conf.js

**Comment by sveneisenschmidt** [comment]
Merged to master.
