### ISSUE TITLE
[feature] Enable overriding of `config.tests` for `run-multiple`

### ISSUE THREAD

**Issue by sveneisenschmidt** [Codeception/CodeceptJS#978]
Hello, first thank you for the work you have put in here!  
(This is the second part of a feature request. For the first part please go to #976.)

**Sidenote**
We at @trivago Leipzig use CodeceptJS for end-to-end testing and are working currently on a simple way to run multiple jobs in parallel without using grep and tags.

**Feature**
A first step into having a working solution is to enable CodeceptJS to load tests not only by grep/tags but also by their concrete file name. As this is already working for the `run` command it would be a useful enhancement to CodeceptJS itself when the user is able to create multiple groups and override inside them the tests that should be run.

The true power with this feature lies in combination with #976. If both features get accepted it will be possible do dynamically create `run-multiple` configuration by the amount of overall scenarios and distribute them evenly between a defined amount of runs. For a working examples please have a look [here](https://github.com/sveneisenschmidt/codeceptjs-boilerplate/blob/master/lib/create-multiple.js) and [here](https://github.com/sveneisenschmidt/codeceptjs-boilerplate/blob/master/codecept.conf.js).

**Technical explaination**
I'd like to propose to extend the `runSuite` function to also pass the `tests` configuration down from the multiple configuration to the CodeceptJS `run`call. 

**Example**
```js
{
  "tests": "./*_test.js",
  "multiple": {
    "default": {
      "browsers": ["chrome", { "browser": "firefox"}]
    },
    "group1": {
      "tests": "./*_group1_test.js",
      "browsers": ["chrome"]
    },
    "group2": {
      "tests": "./*_group2_test.js",
      "browsers": ["chrome"]
    }
  }
}

```

**Todos**
- [x] Add `test-runner` service in `docker-compose.yml`
- [x] Write test case and verify nothing is breaking
- [x] Adapt `runSuite` function
- [x] Create a Pull Request in the fork https://github.com/sveneisenschmidt/CodeceptJS/pull/2
- [x] Feedback by maintainers
- [x] Create a Pull Request in this repository

What do you think? 

PS: If you want to see why glob support is needed please look at my demo repository:

- https://github.com/sveneisenschmidt/codeceptjs-boilerplate#todo
- https://github.com/sveneisenschmidt/codeceptjs-boilerplate/blob/master/lib/create-multiple.js
- https://github.com/sveneisenschmidt/codeceptjs-boilerplate/blob/master/codecept.conf.js

**Comment by DavertMik** [comment]
Thanks, for the feedback and thanks for implementing this feature. Yes, this is something that is really needed to simplify parallel execution. I'm really excited about the implementation and the level of information you provided!

Yes, please send both pull requests. Sure, I'd like to merge them all unless @APshenkin or @reubenmiller have any comments.

What's more interesting to discuss is how to

> dynamically create run-multiple configuration by the amount of overall scenarios and distribute them evenly between a defined amount of runs. 

I saw your implementation and it looks nice but it can be moved inside codeceptjs and its API can be simplified to be flexible and simple for use. So my proposals are:

* create-multiple/with-multiple should be a class inside codeceptjs in `lib/`
* its configuration could be set in `codecept.json` under `multiple` section (without dynamical features).

Please also [join our Slack](https://join.slack.com/t/codeceptjs/shared_invite/enQtMzA5OTM4NDM2MzA4LTNiMTE5YzNlMjQyNWYwZjAzODE3ZTI1MmVkYjY0YTYyNDZmMWJjM2VlODg3NTQzYzM2OGE5ZmIwODFjODk1MzI) to discuss the development process

**Comment by reubenmiller** [comment]
I definitely don’t have any objections to the proposals. My first impressions were very positive, we’ll just have to work out how to document it cleanly for users with no so much technical know how. But I love the direction that we’re going in with the dynamic rurn-multiple command. Though maybe we’ll have to open a discussion about merging reports (I.e. mochawesome reports)

**Comment by DavertMik** [comment]
Yes, this looks like a good start to a long road. So that's why I'd propose to add @sveneisenschmidt to our dev channel in Slack and continue there.

**Comment by sveneisenschmidt** [comment]
@DavertMik @reubenmiller Thank you for the great feedback! I filed the PRs but got violations by `Hound`. Going to fix them soon.

I will join Slack and then we can further discuss how to implement dynamic multiple runs in a simple way. I have already an idea, but it relies on these concrete features.

Thank you!

**Comment by sveneisenschmidt** [comment]
Merged to master.
